Repository AY2223S1-CS2103T-W13-2/tp, pull requests merged in 2022-11, with the labels that each got.

#189 UG updates + changed viewIncome date limitations
  docs/UserGuide.md
  docs/images/GUI.png
  docs/img.png
  src/main/java/longtimenosee/commons/core/Messages.java
  src/main/java/longtimenosee/logic/commands/AddCommand.java
  src/main/java/longtimenosee/logic/commands/AddEventCommand.java
  src/main/java/longtimenosee/logic/commands/EditCommand.java
  src/main/java/longtimenosee/logic/commands/ExitCommand.java
  src/main/java/longtimenosee/logic/commands/ListCommand.java
  src/main/java/longtimenosee/logic/commands/ListEventsCommand.java
  src/main/java/longtimenosee/logic/commands/PolicyAddCommand.java
  src/main/java/longtimenosee/logic/commands/PolicyListCommand.java
  src/main/java/longtimenosee/logic/commands/ViewIncomeCommand.java
  src/main/java/longtimenosee/logic/parser/ViewIncomeCommandParser.java
Labels: priority.Medium

#190 Person and event model test cases
  docs/UserGuide.md
  docs/images/allEventsSample.png
  docs/team/cowlinn.md
  src/main/java/longtimenosee/logic/parser/ParserUtil.java
  src/main/java/longtimenosee/model/person/Income.java
  src/main/java/longtimenosee/model/person/RiskAppetite.java
  src/main/java/longtimenosee/storage/JsonAdaptedPerson.java
  src/main/java/longtimenosee/ui/EventCard.java
  src/test/java/longtimenosee/logic/commands/CommandTestUtil.java
  src/test/java/longtimenosee/model/person/BirthdayTest.java
  src/test/java/longtimenosee/model/person/IncomeTest.java
  src/test/java/longtimenosee/model/person/PhoneTest.java
  src/test/java/longtimenosee/model/person/RiskAppetiteTest.java
Labels: priority.High

#191 Update user guide and add project portfolio page
  docs/UserGuide.md
  docs/images/findClientExample.png
  docs/team/marcusczh.md
Labels: type.Documentation

#193 Tests for Events class and its Commands
  src/main/java/longtimenosee/logic/commands/CalendarCommand.java
  src/main/java/longtimenosee/model/event/Duration.java
  src/main/java/longtimenosee/model/event/Event.java
  src/test/java/longtimenosee/logic/commands/AddEventCommandTest.java
  src/test/java/longtimenosee/logic/commands/CalendarCommandTest.java
  src/test/java/longtimenosee/logic/commands/CommandTestUtil.java
  src/test/java/longtimenosee/logic/commands/DeleteEventCommandTest.java
  src/test/java/longtimenosee/logic/commands/ListEventsCommandTest.java
  src/test/java/longtimenosee/model/event/DateTest.java
  src/test/java/longtimenosee/model/event/DescriptionTest.java
  src/test/java/longtimenosee/model/event/DurationTest.java
  src/test/java/longtimenosee/model/event/EventTest.java
  src/test/java/longtimenosee/testutil/EventBuilder.java
  src/test/java/longtimenosee/testutil/TypicalEvents.java
Labels: priority.Medium

#187 Fix bug with assign/deleteAssigned not working on edited clients.
  src/main/java/longtimenosee/model/person/Person.java
Labels: type.Bug

#199 Add test cases for FindEventCommand and Event predicates
  src/main/java/longtimenosee/model/event/predicate/DescriptionContainsKeywordsPredicate.java
  src/main/java/longtimenosee/model/event/predicate/EventDateMatchesInputPredicate.java
  src/main/java/longtimenosee/model/event/predicate/NameInEventContainsKeywordsPredicate.java
  src/main/java/longtimenosee/model/person/predicate/AddressContainsInputPredicate.java
  src/main/java/longtimenosee/model/person/predicate/PhoneContainsNumberPredicate.java
  src/test/java/longtimenosee/logic/commands/FindEventCommandTest.java
  src/test/java/longtimenosee/model/event/predicate/DescriptionContainsKeywordsPredicateTest.java
  src/test/java/longtimenosee/model/event/predicate/EventDateMatchesInputPredicateTest.java
  src/test/java/longtimenosee/model/event/predicate/NameInEventContainsKeywordsPredicateTest.java
Labels: priority.Medium

#198 Fix bugs for PE-D and add PPP
  docs/UserGuide.md
  docs/images/policies.png
  docs/team/ssatu.md
  src/main/java/longtimenosee/logic/commands/AddEventCommand.java
  src/main/java/longtimenosee/logic/commands/DeleteCommand.java
  src/main/java/longtimenosee/logic/commands/DeleteEventCommand.java
  src/main/java/longtimenosee/logic/commands/EditCommand.java
  src/main/java/longtimenosee/logic/commands/PolicyAddCommand.java
  src/main/java/longtimenosee/logic/commands/PolicyAssignCommand.java
  src/main/java/longtimenosee/logic/commands/PolicyAssignedListCommand.java
  src/main/java/longtimenosee/logic/commands/PolicyDeleteAssignedCommand.java
  src/main/java/longtimenosee/logic/commands/PolicyDeleteCommand.java
  src/main/java/longtimenosee/logic/commands/ViewPinCommand.java
  src/main/java/longtimenosee/logic/parser/PolicyAssignedDeleteCommandParser.java
  src/main/java/longtimenosee/model/ModelManager.java
  src/main/java/longtimenosee/model/person/UniquePersonList.java
  src/main/java/longtimenosee/model/person/exceptions/PolicyNotFoundException.java
  src/main/java/longtimenosee/model/policy/Commission.java
  src/main/java/longtimenosee/model/policy/Premium.java
  src/main/java/longtimenosee/model/util/SampleDataUtil.java
  src/test/java/longtimenosee/logic/commands/CommandTestUtil.java
  src/test/java/longtimenosee/logic/commands/PolicyAddCommandTest.java
  src/test/java/longtimenosee/logic/commands/PolicyAssignCommandTest.java
  src/test/java/longtimenosee/logic/commands/PolicyAssignedListCommandTest.java
  src/test/java/longtimenosee/logic/commands/PolicyDeleteAssignedCommandTest.java
  src/test/java/longtimenosee/logic/commands/PolicyDeleteCommandTest.java
  src/test/java/longtimenosee/logic/commands/PolicyListCommandTest.java
  src/test/java/longtimenosee/model/person/UniquePersonListTest.java
  src/test/java/longtimenosee/model/person/predicate/RiskAppetiteMatchesInputPredicateTest.java
  src/test/java/longtimenosee/model/policy/AssignedPolicyTest.java
  src/test/java/longtimenosee/model/policy/CommissionTest.java
  src/test/java/longtimenosee/model/policy/CompanyTest.java
  src/test/java/longtimenosee/model/policy/CoveragesTest.java
  src/test/java/longtimenosee/model/policy/PolicyDateTest.java
  src/test/java/longtimenosee/model/policy/PolicyTest.java
  src/test/java/longtimenosee/model/policy/PremiumTest.java
  src/test/java/longtimenosee/model/policy/TitleTest.java
  src/test/java/longtimenosee/model/policy/UniquePolicyListTest.java
  src/test/java/longtimenosee/model/policy/predicate/CompanyMatchesInputPredicateTest.java
  src/test/java/longtimenosee/model/policy/predicate/CoverageMatchesInputPredicateTest.java
  src/test/java/longtimenosee/model/policy/predicate/TitleContainsKeywordsPredicateTest.java
  src/test/java/longtimenosee/testutil/AddressBookBuilder.java
  src/test/java/longtimenosee/testutil/AssignedPolicyBuilder.java
  src/test/java/longtimenosee/testutil/PolicyBuilder.java
  src/test/java/longtimenosee/testutil/TypicalAssignedPolicies.java
  src/test/java/longtimenosee/testutil/TypicalIndexes.java
  src/test/java/longtimenosee/testutil/TypicalPolicies.java
Labels: type.Bug, type.Documentation

#200 Event Parser Test cases
  src/test/java/longtimenosee/logic/commands/CommandTestEventUtil.java
  src/test/java/longtimenosee/logic/parser/AddEventCommandParserTest.java
  src/test/java/longtimenosee/testutil/TypicalEvents.java
Labels: priority.Medium

#195 Test cases for pin, viewPin, viewIncome
  docs/UserGuide.md
  docs/team/loyhongshenggg.md
  src/main/java/longtimenosee/logic/commands/PinCommand.java
  src/main/java/longtimenosee/logic/parser/ViewIncomeCommandParser.java
  src/main/java/longtimenosee/logic/parser/ViewPinCommandParser.java
  src/main/java/longtimenosee/model/Model.java
  src/main/java/longtimenosee/model/ModelManager.java
  src/test/java/longtimenosee/logic/commands/AddCommandTest.java
  src/test/java/longtimenosee/logic/commands/AddEventCommandTest.java
  src/test/java/longtimenosee/logic/commands/CommandTestUtil.java
  src/test/java/longtimenosee/logic/commands/PinCommandTest.java
  src/test/java/longtimenosee/logic/commands/PolicyAddCommandTest.java
  src/test/java/longtimenosee/logic/commands/ViewIncomeCommandTest.java
  src/test/java/longtimenosee/logic/commands/ViewPinCommandTest.java
  src/test/java/longtimenosee/logic/parser/PinCommandParserTest.java
  src/test/java/longtimenosee/logic/parser/ViewIncomeCommandParserTest.java
  src/test/java/longtimenosee/logic/parser/ViewPinCommandParserTest.java
Labels: priority.High

#204 General bugfixing
  src/main/java/longtimenosee/logic/commands/AddEventCommand.java
  src/main/java/longtimenosee/model/AddressBook.java
  src/main/java/longtimenosee/model/ModelManager.java
  src/main/java/longtimenosee/model/event/UniqueEventList.java
  src/main/java/longtimenosee/model/event/exceptions/PersonNotFoundException.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/longtimenosee/logic/commands/AddEventCommandTest.java
  src/test/java/longtimenosee/logic/commands/DeleteCommandTest.java
  src/test/java/longtimenosee/testutil/TypicalPersons.java
Labels: priority.High

#207 Added tests for Event exceptions
  docs/UserGuide.md
  src/main/java/longtimenosee/model/event/exceptions/DuplicateEventException.java
  src/test/java/longtimenosee/logic/commands/AddEventCommandTest.java
  src/test/java/longtimenosee/logic/commands/DeleteEventCommandTest.java
Labels: priority.Medium

#209 Updates to UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AssignPolicyActivityDiagram.puml
  docs/diagrams/AssignPolicySequenceDiagram.puml
  docs/images/AssignPolicyActivityDiagram.png
  docs/images/AssignPolicySequenceDiagram.png
Labels: type.Documentation

#208 Add error handling for invalid events added directly into json storage files
  src/main/java/longtimenosee/logic/commands/AddCommand.java
  src/main/java/longtimenosee/logic/commands/AddEventCommand.java
  src/main/java/longtimenosee/logic/commands/ClearCommand.java
  src/main/java/longtimenosee/logic/commands/DeleteCommand.java
  src/main/java/longtimenosee/logic/commands/DeleteEventCommand.java
  src/main/java/longtimenosee/logic/commands/EditCommand.java
  src/main/java/longtimenosee/logic/commands/EventCommand.java
  src/main/java/longtimenosee/logic/commands/FindCommand.java
  src/main/java/longtimenosee/logic/commands/ListCommand.java
  src/main/java/longtimenosee/logic/commands/ListEventsCommand.java
  src/main/java/longtimenosee/logic/commands/PersonCommand.java
  src/main/java/longtimenosee/logic/commands/PolicyAddCommand.java
  src/main/java/longtimenosee/logic/commands/PolicyAssignCommand.java
  src/main/java/longtimenosee/logic/commands/PolicyAssignedDeleteCommand.java
  src/main/java/longtimenosee/logic/commands/PolicyCommand.java
  src/main/java/longtimenosee/logic/commands/PolicyDeleteCommand.java
  src/main/java/longtimenosee/logic/commands/PolicyListCommand.java
  src/main/java/longtimenosee/logic/commands/SortCommand.java
  src/main/java/longtimenosee/logic/commands/ViewPinCommand.java
  src/main/java/longtimenosee/logic/parser/AddressBookParser.java
  src/main/java/longtimenosee/logic/parser/PolicyAssignedDeleteCommandParser.java
  src/main/java/longtimenosee/model/AddressBook.java
  src/main/java/longtimenosee/storage/JsonAddressBookStorage.java
  src/main/java/longtimenosee/storage/JsonSerializableAddressBook.java
  src/test/java/longtimenosee/logic/commands/PolicyAssignedDeleteCommandTest.java
  src/test/java/longtimenosee/logic/parser/PolicyAssignedDeleteCommandParserTest.java
Labels: priority.Medium

#211 UG DG changes
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/PinSequenceDiagram.puml
  docs/diagrams/ViewIncomeSequenceDiagram.puml
  docs/images/PinSequenceDiagram.png
  docs/images/ViewIncomeSequenceDiagram.png
  docs/team/loyhongshenggg.md
  src/main/java/longtimenosee/commons/core/Messages.java
  src/test/java/longtimenosee/logic/commands/PinCommandTest.java
Labels: priority.High

#212 Colin ug dg update
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddEventActivityDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ModelEventClassDiagram.puml
  docs/images/AddEventActivityDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ModelEventClassDiagram.png
  docs/team/cowlinn.md
Labels: priority.High

#213 Update documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FindActivityDiagram.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/images/FindActivityDiagram.png
  docs/images/FindSequenceDiagram.png
  docs/team/marcusczh.md
Labels: type.Documentation, priority.High

#214 Update UG, DG and PPP
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/reubenchay.md
Labels: type.Documentation

#220 Remaining touch ups to UG
  docs/AboutUs.md
  docs/UserGuide.md
  docs/images/GUI.png
  docs/images/Ui.png
Labels: priority.High
