Repository AY2223S1-CS2103T-W13-2/tp, pull requests merged in 2022-10, with the labels that each got.

#31 Initial Client class
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddClientCommand.java
  src/main/java/seedu/address/logic/parser/AddClientCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/client/Birthday.java
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/model/client/Income.java
  src/main/java/seedu/address/model/client/RiskAppetite.java
  src/main/java/seedu/address/model/client/UniqueClientList.java
  src/main/java/seedu/address/model/client/exceptions/ClientNotFoundException.java
  src/main/java/seedu/address/model/client/exceptions/DuplicateClientException.java
  src/main/java/seedu/address/storage/JsonAdaptedClient.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: priority.Medium

#32 major UI/UX changes
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/StatusBarFooter.fxml
Labels: type.Enhancement

#38 Add Sort Command
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Story

#41 Create policy class
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddPolicyCommand.java
  src/main/java/seedu/address/logic/commands/PolicyCommand.java
  src/main/java/seedu/address/logic/parser/AddPolicyCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/client/AssignedPolicy.java
  src/main/java/seedu/address/model/policy/Commission.java
  src/main/java/seedu/address/model/policy/Company.java
  src/main/java/seedu/address/model/policy/Coverage.java
  src/main/java/seedu/address/model/policy/Policy.java
  src/main/java/seedu/address/model/policy/Premium.java
  src/main/java/seedu/address/model/policy/Title.java
  src/main/java/seedu/address/model/policy/UniquePolicyList.java
  src/main/java/seedu/address/model/policy/exceptions/DuplicatePolicyException.java
  src/main/java/seedu/address/model/policy/exceptions/PolicyNotFoundException.java
  src/main/java/seedu/address/storage/JsonAdaptedCoverage.java
  src/main/java/seedu/address/storage/JsonAdaptedPolicy.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PolicyCard.java
  src/main/java/seedu/address/ui/PolicyListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PolicyListCard.fxml
  src/main/resources/view/PolicyListPanel.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: type.Story, priority.Medium

#44 Branch sort fix
  docs/team/reubenchay.md
  src/main/java/seedu/address/model/person/UniquePersonList.java
Labels: type.Documentation, priority.Low

#45 Colin test client delete
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteClientCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteClientCommandParser.java
Labels: priority.Medium

#48 Pin feature with UI bug fix
  docs/AboutUs.md
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/PinCommand.java
  src/main/java/seedu/address/logic/commands/ViewPinCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/PinCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewPinCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/PinnedPersonPredicate.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: priority.Medium

#49 Update sort command to work for Client class
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/client/UniqueClientList.java
Labels: priority.Medium

#52 Add functionality to switch between showing policies and clients
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/cowlinn.md
  docs/team/reubenchay.md
  docs/team/ssatu.md
  src/main/java/seedu/address/logic/commands/AddClientCommand.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddPolicyCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DeleteClientCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/PersonCommand.java
  src/main/java/seedu/address/logic/commands/PinCommand.java
  src/main/java/seedu/address/logic/commands/PolicyCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/ViewPinCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/PolicyListPanel.fxml
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
Labels: type.Story, priority.Medium

#54 Convert client back to person
  src/main/java/longtimenosee/logic/Logic.java
  src/main/java/longtimenosee/logic/LogicManager.java
  src/main/java/longtimenosee/logic/commands/AddClientCommand.java
  src/main/java/longtimenosee/logic/commands/AddCommand.java
  src/main/java/longtimenosee/logic/commands/DeleteClientCommand.java
  src/main/java/longtimenosee/logic/commands/EditCommand.java
  src/main/java/longtimenosee/logic/parser/AddClientCommandParser.java
  src/main/java/longtimenosee/logic/parser/AddCommandParser.java
  src/main/java/longtimenosee/logic/parser/AddressBookParser.java
  src/main/java/longtimenosee/logic/parser/CliSyntax.java
  src/main/java/longtimenosee/logic/parser/DeleteClientCommandParser.java
  src/main/java/longtimenosee/logic/parser/EditCommandParser.java
  src/main/java/longtimenosee/logic/parser/ParserUtil.java
  src/main/java/longtimenosee/model/AddressBook.java
  src/main/java/longtimenosee/model/Model.java
  src/main/java/longtimenosee/model/ModelManager.java
  src/main/java/longtimenosee/model/ReadOnlyAddressBook.java
  src/main/java/longtimenosee/model/client/Client.java
  src/main/java/longtimenosee/model/client/Income.java
  src/main/java/longtimenosee/model/client/UniqueClientList.java
  src/main/java/longtimenosee/model/client/exceptions/ClientNotFoundException.java
  src/main/java/longtimenosee/model/client/exceptions/DuplicateClientException.java
  src/main/java/longtimenosee/model/person/AssignedPolicy.java
  src/main/java/longtimenosee/model/person/Birthday.java
  src/main/java/longtimenosee/model/person/Income.java
  src/main/java/longtimenosee/model/person/Person.java
  src/main/java/longtimenosee/model/person/RiskAppetite.java
  src/main/java/longtimenosee/model/policy/Policy.java
  src/main/java/longtimenosee/model/util/SampleDataUtil.java
  src/main/java/longtimenosee/storage/JsonAdaptedClient.java
  src/main/java/longtimenosee/storage/JsonAdaptedPerson.java
  src/main/java/longtimenosee/storage/JsonSerializableAddressBook.java
  src/main/java/longtimenosee/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/longtimenosee/logic/LogicManagerTest.java
  src/test/java/longtimenosee/logic/commands/AddCommandTest.java
  src/test/java/longtimenosee/logic/commands/CommandTestUtil.java
  src/test/java/longtimenosee/logic/parser/AddCommandParserTest.java
  src/test/java/longtimenosee/logic/parser/EditCommandParserTest.java
  src/test/java/longtimenosee/model/AddressBookTest.java
  src/test/java/longtimenosee/storage/JsonAdaptedPersonTest.java
  src/test/java/longtimenosee/storage/JsonAddressBookStorageTest.java
  src/test/java/longtimenosee/storage/StorageManagerTest.java
  src/test/java/longtimenosee/testutil/EditPersonDescriptorBuilder.java
  src/test/java/longtimenosee/testutil/PersonBuilder.java
  src/test/java/longtimenosee/testutil/PersonUtil.java
  src/test/java/longtimenosee/testutil/TypicalPersons.java
Labels: priority.High

#55 Extend find command
  src/main/java/longtimenosee/logic/commands/FindCommand.java
  src/main/java/longtimenosee/logic/commands/ViewPinCommand.java
  src/main/java/longtimenosee/logic/parser/FindCommandParser.java
  src/main/java/longtimenosee/logic/parser/ViewPinCommandParser.java
  src/main/java/longtimenosee/model/person/predicate/AddressMatchesInputPredicate.java
  src/main/java/longtimenosee/model/person/predicate/EmailMatchesInputPredicate.java
  src/main/java/longtimenosee/model/person/predicate/NameContainsKeywordsPredicate.java
  src/main/java/longtimenosee/model/person/predicate/PhoneMatchesNumberPredicate.java
  src/main/java/longtimenosee/model/person/predicate/PinnedPersonPredicate.java
  src/main/java/longtimenosee/model/person/predicate/TagContainsKeywordsPredicate.java
  src/test/java/longtimenosee/logic/commands/CommandTestUtil.java
  src/test/java/longtimenosee/logic/commands/FindCommandTest.java
  src/test/java/longtimenosee/logic/parser/AddressBookParserTest.java
  src/test/java/longtimenosee/logic/parser/FindCommandParserTest.java
  src/test/java/longtimenosee/model/ModelManagerTest.java
  src/test/java/longtimenosee/model/person/NameContainsKeywordsPredicateTest.java
Labels: type.Enhancement

#60 Bugfixes with JsonAdaptedPerson
  src/main/java/longtimenosee/logic/parser/EditCommandParser.java
  src/main/java/longtimenosee/model/person/RiskAppetite.java
  src/main/java/longtimenosee/storage/JsonAdaptedPerson.java
Labels: type.Bug

#59 Add more metrics for sort command
  src/main/java/longtimenosee/logic/commands/SortCommand.java
  src/main/java/longtimenosee/model/person/Birthday.java
  src/main/java/longtimenosee/model/person/Email.java
  src/main/java/longtimenosee/model/person/Income.java
  src/main/java/longtimenosee/model/person/RiskAppetite.java
Labels: type.Enhancement, priority.Medium

#63 Update policy functionality.
  src/main/java/longtimenosee/commons/core/Messages.java
  src/main/java/longtimenosee/logic/commands/EditCommand.java
  src/main/java/longtimenosee/logic/commands/PolicyAddCommand.java
  src/main/java/longtimenosee/logic/commands/PolicyAssignCommand.java
  src/main/java/longtimenosee/logic/commands/PolicyDeleteCommand.java
  src/main/java/longtimenosee/logic/commands/PolicyListCommand.java
  src/main/java/longtimenosee/logic/parser/AddressBookParser.java
  src/main/java/longtimenosee/logic/parser/AssignPolicyCommandParser.java
  src/main/java/longtimenosee/logic/parser/CliSyntax.java
  src/main/java/longtimenosee/logic/parser/ParserUtil.java
  src/main/java/longtimenosee/logic/parser/PolicyAddCommandParser.java
  src/main/java/longtimenosee/logic/parser/PolicyAssignCommandParser.java
  src/main/java/longtimenosee/logic/parser/PolicyDeleteCommandParser.java
  src/main/java/longtimenosee/model/person/Person.java
  src/main/java/longtimenosee/model/policy/AssignedPolicy.java
  src/main/java/longtimenosee/model/policy/Policy.java
  src/main/java/longtimenosee/model/policy/PolicyDate.java
  src/main/java/longtimenosee/model/policy/Premium.java
  src/main/java/longtimenosee/storage/JsonAdaptedAssignedPolicy.java
  src/main/java/longtimenosee/storage/JsonAdaptedPerson.java
  src/test/java/longtimenosee/storage/JsonAdaptedPersonTest.java
Labels: type.Story, priority.High

#69 Change policy display to include full company name
  src/main/java/longtimenosee/ui/PolicyCard.java
Labels: priority.Low

#74 v1.3 feature - View Income
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/diagrams/PinActivityDiagram.puml
  docs/diagrams/PinSequenceDiagram.puml
  docs/diagrams/ViewPinActivityDiagram.puml
  docs/images/PinActivityDiagram.png
  docs/images/PinSequenceDiagram.png
  docs/images/ViewPinActivityDiagram.png
  docs/images/sampleGUI.png
  docs/images/viewIncome.png
  docs/images/viewPin.png
  docs/team/loyhongshenggg.md
  src/main/java/longtimenosee/commons/core/GuiSettings.java
  src/main/java/longtimenosee/logic/Logic.java
  src/main/java/longtimenosee/logic/LogicManager.java
  src/main/java/longtimenosee/logic/commands/AddCommand.java
  src/main/java/longtimenosee/logic/commands/ClearCommand.java
  src/main/java/longtimenosee/logic/commands/CommandResult.java
  src/main/java/longtimenosee/logic/commands/DeleteCommand.java
  src/main/java/longtimenosee/logic/commands/EditCommand.java
  src/main/java/longtimenosee/logic/commands/ExitCommand.java
  src/main/java/longtimenosee/logic/commands/FindCommand.java
  src/main/java/longtimenosee/logic/commands/HelpCommand.java
  src/main/java/longtimenosee/logic/commands/ListCommand.java
  src/main/java/longtimenosee/logic/commands/PersonCommand.java
  src/main/java/longtimenosee/logic/commands/PinCommand.java
  src/main/java/longtimenosee/logic/commands/PolicyAddCommand.java
  src/main/java/longtimenosee/logic/commands/PolicyAssignCommand.java
  src/main/java/longtimenosee/logic/commands/PolicyCommand.java
  src/main/java/longtimenosee/logic/commands/PolicyDeleteCommand.java
  src/main/java/longtimenosee/logic/commands/PolicyListCommand.java
  src/main/java/longtimenosee/logic/commands/SortCommand.java
  src/main/java/longtimenosee/logic/commands/ViewIncomeCommand.java
  src/main/java/longtimenosee/logic/commands/ViewPinCommand.java
  src/main/java/longtimenosee/logic/parser/AddressBookParser.java
  src/main/java/longtimenosee/logic/parser/PinCommandParser.java
  src/main/java/longtimenosee/logic/parser/ViewIncomeCommandParser.java
  src/main/java/longtimenosee/model/Model.java
  src/main/java/longtimenosee/model/ModelManager.java
  src/main/java/longtimenosee/model/policy/AssignedPolicy.java
  src/main/java/longtimenosee/model/policy/Commission.java
  src/main/java/longtimenosee/model/policy/FinancialAdvisorIncome.java
  src/main/java/longtimenosee/model/policy/Policy.java
  src/main/java/longtimenosee/ui/IncomeChart.java
  src/main/java/longtimenosee/ui/MainWindow.java
  src/main/java/longtimenosee/ui/UiManager.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/LineGraph.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/longtimenosee/logic/commands/AddCommandTest.java
  src/test/java/longtimenosee/logic/commands/CommandResultTest.java
  src/test/java/longtimenosee/logic/commands/CommandTestUtil.java
  src/test/java/longtimenosee/logic/commands/ExitCommandTest.java
  src/test/java/longtimenosee/logic/commands/HelpCommandTest.java
Labels: priority.High

#70 DG Update Model and AddCommand
  docs/DeveloperGuide.md
  docs/diagrams/AddEventActivityDiagram.puml
  docs/diagrams/ModelEventClassDiagram.puml
  docs/images/AddEventActivityDiagram.png
  docs/images/ModelEventClassDiagram.png
Labels: priority.Medium

#73 Update developer guide
  docs/DeveloperGuide.md
  docs/diagrams/FindActivityDiagram.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/UniquePolicyListClassDiagram.puml
  docs/images/FindActivityDiagram.png
  docs/images/FindSequenceDiagram.png
  docs/images/UniquePolicyListClassDiagram.png
Labels: type.Documentation

#67 Add Event Class
  src/main/java/longtimenosee/commons/core/Messages.java
  src/main/java/longtimenosee/logic/Logic.java
  src/main/java/longtimenosee/logic/LogicManager.java
  src/main/java/longtimenosee/logic/commands/AddEventCommand.java
  src/main/java/longtimenosee/logic/commands/CalendarCommand.java
  src/main/java/longtimenosee/logic/commands/CommandResult.java
  src/main/java/longtimenosee/logic/commands/DeleteCommand.java
  src/main/java/longtimenosee/logic/commands/DeleteEventCommand.java
  src/main/java/longtimenosee/logic/commands/EditCommand.java
  src/main/java/longtimenosee/logic/commands/ExitCommand.java
  src/main/java/longtimenosee/logic/commands/HelpCommand.java
  src/main/java/longtimenosee/logic/commands/ListEventsCommand.java
  src/main/java/longtimenosee/logic/commands/PersonCommand.java
  src/main/java/longtimenosee/logic/commands/PolicyAddCommand.java
  src/main/java/longtimenosee/logic/commands/PolicyAssignCommand.java
  src/main/java/longtimenosee/logic/commands/ViewIncomeCommand.java
  src/main/java/longtimenosee/logic/parser/AddEventCommandParser.java
  src/main/java/longtimenosee/logic/parser/AddressBookParser.java
  src/main/java/longtimenosee/logic/parser/CliSyntax.java
  src/main/java/longtimenosee/logic/parser/DeleteEventCommandParser.java
  src/main/java/longtimenosee/logic/parser/ParserUtil.java
  src/main/java/longtimenosee/model/AddressBook.java
  src/main/java/longtimenosee/model/Model.java
  src/main/java/longtimenosee/model/ModelManager.java
  src/main/java/longtimenosee/model/ReadOnlyAddressBook.java
  src/main/java/longtimenosee/model/event/Date.java
  src/main/java/longtimenosee/model/event/Description.java
  src/main/java/longtimenosee/model/event/Duration.java
  src/main/java/longtimenosee/model/event/Event.java
  src/main/java/longtimenosee/model/event/PersonName.java
  src/main/java/longtimenosee/model/event/UniqueEventList.java
  src/main/java/longtimenosee/model/event/exceptions/DuplicateEventException.java
  src/main/java/longtimenosee/model/event/exceptions/EventNotFoundException.java
  src/main/java/longtimenosee/model/event/exceptions/OverlapEventException.java
  src/main/java/longtimenosee/model/event/predicate/WithinNextSevenDays.java
  src/main/java/longtimenosee/model/person/Birthday.java
  src/main/java/longtimenosee/model/person/Person.java
  src/main/java/longtimenosee/model/person/UniquePersonList.java
  src/main/java/longtimenosee/storage/JsonAdaptedEvent.java
  src/main/java/longtimenosee/storage/JsonSerializableAddressBook.java
  src/main/java/longtimenosee/ui/EventCard.java
  src/main/java/longtimenosee/ui/EventListPanel.java
  src/main/java/longtimenosee/ui/MainWindow.java
  src/main/resources/view/EventListCard.fxml
  src/main/resources/view/EventListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/longtimenosee/logic/commands/AddCommandTest.java
  src/test/java/longtimenosee/logic/commands/CommandResultTest.java
  src/test/java/longtimenosee/logic/commands/ExitCommandTest.java
  src/test/java/longtimenosee/logic/commands/HelpCommandTest.java
  src/test/java/longtimenosee/model/AddressBookTest.java
Labels: priority.High, priority.Medium, priority.Low

#79 Modify Model component details
  docs/DeveloperGuide.md
  docs/diagrams/ModelPolicyClassDiagram.puml
  docs/images/ModelPolicyClassDiagram.png
  docs/images/UniquePolicyListClassDiagram.png
Labels: type.Documentation

#76 Update DG with Storage class diagram and assign implementation.
  docs/DeveloperGuide.md
  docs/diagrams/AssignPolicySequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/AssignPolicySequenceDiagram.png
  docs/images/StorageClassDiagram.png
  src/main/java/longtimenosee/logic/commands/PolicyAddCommand.java
  src/main/java/longtimenosee/logic/parser/AssignPolicyCommandParser.java
Labels: type.Documentation

#80 Modify input validation
  src/main/java/longtimenosee/logic/parser/ParserUtil.java
  src/main/java/longtimenosee/model/person/RiskAppetite.java
  src/main/java/longtimenosee/model/policy/Company.java
  src/main/java/longtimenosee/model/policy/Coverage.java
  src/main/java/longtimenosee/model/policy/Title.java
Labels: priority.High

#81 Find policy command
  src/main/java/longtimenosee/commons/core/Messages.java
  src/main/java/longtimenosee/logic/commands/FindPolicyCommand.java
  src/main/java/longtimenosee/logic/parser/AddressBookParser.java
  src/main/java/longtimenosee/logic/parser/FindPolicyCommandParser.java
  src/main/java/longtimenosee/model/policy/predicate/CompanyMatchesInputPredicate.java
  src/main/java/longtimenosee/model/policy/predicate/CoverageMatchesInputPredicate.java
  src/main/java/longtimenosee/model/policy/predicate/TitleContainsKeywordsPredicate.java
  src/test/java/longtimenosee/logic/parser/FindPolicyCommandParserTest.java
Labels: priority.Medium

#86 Add functionality to view assigned policies of a client, delete them and delete policies itself.
  src/main/java/longtimenosee/commons/core/Messages.java
  src/main/java/longtimenosee/logic/commands/AddCommand.java
  src/main/java/longtimenosee/logic/commands/CommandResult.java
  src/main/java/longtimenosee/logic/commands/DeleteCommand.java
  src/main/java/longtimenosee/logic/commands/EditCommand.java
  src/main/java/longtimenosee/logic/commands/FindCommand.java
  src/main/java/longtimenosee/logic/commands/ListCommand.java
  src/main/java/longtimenosee/logic/commands/ListEventsCommand.java
  src/main/java/longtimenosee/logic/commands/PersonCommand.java
  src/main/java/longtimenosee/logic/commands/PolicyAssignCommand.java
  src/main/java/longtimenosee/logic/commands/PolicyAssignedListCommand.java
  src/main/java/longtimenosee/logic/commands/PolicyCommand.java
  src/main/java/longtimenosee/logic/commands/PolicyDeleteAssignedCommand.java
  src/main/java/longtimenosee/logic/commands/PolicyDeleteCommand.java
  src/main/java/longtimenosee/logic/commands/PolicyListCommand.java
  src/main/java/longtimenosee/logic/parser/AddressBookParser.java
  src/main/java/longtimenosee/logic/parser/PolicyAssignedDeleteCommandParser.java
  src/main/java/longtimenosee/logic/parser/PolicyAssignedListCommandParser.java
  src/main/java/longtimenosee/model/AddressBook.java
  src/main/java/longtimenosee/model/person/Person.java
  src/main/java/longtimenosee/model/policy/AssignedPolicy.java
  src/main/java/longtimenosee/ui/MainWindow.java
  src/test/java/longtimenosee/logic/LogicManagerTest.java
Labels: type.Story

#89 Replace PersonName class with Name
  src/main/java/longtimenosee/logic/commands/AddEventCommand.java
  src/main/java/longtimenosee/logic/parser/AddEventCommandParser.java
  src/main/java/longtimenosee/logic/parser/CliSyntax.java
  src/main/java/longtimenosee/logic/parser/ParserUtil.java
  src/main/java/longtimenosee/model/event/Date.java
  src/main/java/longtimenosee/model/event/Event.java
  src/main/java/longtimenosee/model/event/PersonName.java
  src/main/java/longtimenosee/model/event/UniqueEventList.java
  src/main/java/longtimenosee/storage/JsonAdaptedEvent.java
  src/main/java/longtimenosee/ui/EventCard.java
Labels: priority.Medium

#91 Updated User Guide
  docs/UserGuide.md
Labels: type.Documentation, priority.High

#83 Add find event command to allow users to search for events
  src/main/java/longtimenosee/commons/core/Messages.java
  src/main/java/longtimenosee/logic/commands/FindEventCommand.java
  src/main/java/longtimenosee/logic/parser/AddressBookParser.java
  src/main/java/longtimenosee/logic/parser/FindEventCommandParser.java
  src/main/java/longtimenosee/model/event/predicate/DescriptionContainsKeywordsPredicate.java
  src/main/java/longtimenosee/model/event/predicate/EventDateMatchesInputPredicate.java
  src/main/java/longtimenosee/model/event/predicate/NameInEventContainsKeywordsPredicate.java
  src/test/java/longtimenosee/logic/parser/FindEventCommandParserTest.java
Labels: priority.Medium

#94 Update user guide with search related features
  docs/UserGuide.md
Labels: type.Documentation

#98 Add input validation to assign policy command.
  src/main/java/longtimenosee/logic/parser/PolicyAssignCommandParser.java
  src/main/java/longtimenosee/model/policy/AssignedPolicy.java
  src/main/java/longtimenosee/model/policy/PolicyDate.java
  src/main/java/longtimenosee/model/policy/Premium.java
Labels: type.Bug, priority.High

#99 Update UG with policy features, update coverages with investment.
  docs/UserGuide.md
  src/main/java/longtimenosee/logic/commands/PolicyListCommand.java
  src/main/java/longtimenosee/model/policy/AssignedPolicy.java
  src/main/java/longtimenosee/model/policy/Coverage.java
  src/main/java/longtimenosee/model/policy/PolicyDate.java
  src/main/java/longtimenosee/model/policy/Premium.java
Labels: type.Documentation

#97 Input validation for viewIncome and minor bug fixes
  docs/AboutUs.md
  docs/UserGuide.md
  docs/images/helpMessage.png
  docs/team/loyhongshenggg.md
  src/main/java/longtimenosee/commons/core/Messages.java
  src/main/java/longtimenosee/commons/core/index/Index.java
  src/main/java/longtimenosee/logic/commands/AddCommand.java
  src/main/java/longtimenosee/logic/commands/PolicyDeleteAssignedCommand.java
  src/main/java/longtimenosee/logic/commands/ViewIncomeCommand.java
  src/main/java/longtimenosee/logic/parser/ViewIncomeCommandParser.java
  src/main/java/longtimenosee/logic/parser/exceptions/InvalidYearException.java
  src/main/java/longtimenosee/model/policy/Commission.java
  src/main/java/longtimenosee/model/policy/FinancialAdvisorIncome.java
  src/main/java/longtimenosee/ui/HelpWindow.java
  src/main/java/longtimenosee/ui/PersonCard.java
  src/main/java/longtimenosee/ui/ResultDisplay.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/LineGraph.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/StatusBarFooter.fxml
Labels: type.Bug

#101 Client and event input validation
  src/main/java/longtimenosee/logic/parser/ParserUtil.java
  src/main/java/longtimenosee/model/event/Date.java
  src/main/java/longtimenosee/model/event/Description.java
  src/main/java/longtimenosee/model/event/Event.java
  src/main/java/longtimenosee/model/person/Birthday.java
  src/main/java/longtimenosee/model/person/Name.java
  src/main/java/longtimenosee/model/person/Person.java
  src/main/java/longtimenosee/model/person/Phone.java
  src/main/java/longtimenosee/model/policy/AssignedPolicy.java
  src/main/java/longtimenosee/model/policy/Policy.java
  src/main/java/longtimenosee/storage/JsonAdaptedEvent.java
  src/main/java/longtimenosee/storage/JsonAdaptedPerson.java
Labels: priority.Medium

#104 Reduce font size of ResultDisplay
  src/main/resources/view/ResultDisplay.fxml
Labels: priority.High

#106 Fix bug for policy code
  docs/DeveloperGuide.md
  src/main/resources/view/DarkTheme.css
Labels: type.Bug

#172 Test person predicates
  src/main/java/longtimenosee/logic/parser/FindCommandParser.java
  src/main/java/longtimenosee/model/person/predicate/AddressContainsInputPredicate.java
  src/main/java/longtimenosee/model/person/predicate/PhoneContainsNumberPredicate.java
  src/test/java/longtimenosee/logic/parser/FindCommandParserTest.java
  src/test/java/longtimenosee/model/person/predicate/AddressMatchesInputPredicateTest.java
  src/test/java/longtimenosee/model/person/predicate/BirthdayMatchesInputPredicateTest.java
  src/test/java/longtimenosee/model/person/predicate/EmailMatchesInputPredicateTest.java
  src/test/java/longtimenosee/model/person/predicate/IncomeMatchesInputPredicateTest.java
  src/test/java/longtimenosee/model/person/predicate/NameContainsKeywordsPredicateTest.java
  src/test/java/longtimenosee/model/person/predicate/PhoneContainsNumberPredicateTest.java
  src/test/java/longtimenosee/model/person/predicate/RiskAppetiteMatchesInputPredicateTest.java
  src/test/java/longtimenosee/model/person/predicate/TagContainsKeywordsPredicateTest.java
Labels: priority.Medium

#171 UG Bugs + AddCommand buggy error message
  docs/UserGuide.md
  src/main/java/longtimenosee/logic/commands/AddCommand.java
Labels: priority.Medium

#182 Fix UG and Sort Feature bugs
  docs/UserGuide.md
  docs/images/JsonExample.png
  src/main/java/longtimenosee/model/person/Email.java
  src/main/java/longtimenosee/model/person/Name.java
Labels: priority.High

#188 UG update
  docs/UserGuide.md
  docs/images/SortEmailExample.png
  docs/team/reubenchay.md
Labels: type.Documentation, priority.Medium
